tester: search_based  # 
common:
  seed: None
  termination: "n_gen"
  budget: 5000

search_based:
  pop_size: 100 
  n_offspring: 100 
  algorithm: "ga"
  crossover: "sbx"
  mutation: "pm"
  crossover_prob: 0.9
  mutation_prob: 0.9
  problem_name: 'dynamic_testing'
  duplicate_threshold: 0.05
